### ISSUE TITLE
Move to radareorg namespace?

### ISSUE THREAD

**Issue by XVilka** [radare/r2jp#6]
Since it's community, IMHO it fits better. @radare @unixfreaxjp what do you think?

**Comment by radare** [comment]
Yeah seems reasonable as long as radare/ is my account and aims to be for code not data

**Comment by unixfreaxjp** [comment]
most of key members now is having git and we've just started r2jp , at this moment maybe it'll be more msgs than codes, the point is to make members get used to git/dev/q-a environment & start launch some projects (we have some plans). we will write several wiki (in japanese) which is part of radare2 docs dev too actually, better to be close to source. changing it now will make us lose the pace that I don't think I can drive it back to the current pace.

**Comment by unixfreaxjp** [comment]
i am closing this issue if not having further discussion.

**Comment by Maijin** [comment]
Would make more sense indeed, and you can create a r2jp team https://github.com/orgs/radareorg/teams

**Comment by radare** [comment]
Agree on that. Moving that is just a matter of pressing a button. All contributors should keep their permissions and iirc github redirects links in case of using the old link. 

For code projects we must go for radare/

The org is more about coordinating and organizing

**Comment by Maijin** [comment]
No they should use radareorg too for code so coordination and organization can be used from there that's the whole point..

**Comment by unixfreaxjp** [comment]
> Would make more sense indeed, and you can create a r2jp team https://github.com/orgs/radareorg/teams

1) I don't know about this matter until now

> Agree on that. Moving that is just a matter of pressing a button. 

I need the guidance for the moving for new users. I the "one button pressing" you advised and ending up w/page says: **"You’re not a member of any teams in this organization. "**

So I guess is a little bit more complicated than just pressing a button.

2) Hmm. These two points below has a contradiction. Please pick which one to be applied:

> @radare : For code projects we must go for radare/ 

> @Maijin : No they should use radareorg too for code so coordination and organization 

3) People here don't like much changes after committing something, it is not in our culture, but if changes has to be done, it has to be w/guidance, announcement and provide something for the changes to be easier for them. Frankly, it is only adding my load specially if we don't make it clear beforehand. Yet, if there is too much complication in github, r2jp can start using sites in Japan instead for not losing pace. We have plenty of national resource to be use for this. But that means separation of teams and I really don't like that idea,

So please answer these questions for moving:

- How to move to radareorg, when, and step that has to be done for our ppl in github 
- What is the requirement needed for the current user to follow the move? 
- We hope to have the our stuff in radare/r2jp arrangement to be mirrored in the new place, possible or not? i.e.: For the tool's (plugin, addon etc) code and project, will be in r2jp
- When (time frame) expected for this movement.
- Who will be contacted for the assistance from your side for this matter. In our side I will try my best.

Thanks

**Comment by unixfreaxjp** [comment]
それでは、r2jpの本レポをradareからradareorgに移動します。
1. 予定：
今日まで足りないregistの方には登録が必要、明日から自動転送を行う予定です。
2．影響：
メンバース、Issues, projectなどの影響がありません。
3. やる事:
既に登録した人はありません、未だ登録してない人は今日迄登録しないと移動にはフォローされない可能性がありますのでご注意ください。
4. 移動 いついてのお問い合わせ/連絡先:
@unixfreaxjp @radare 

以上

**Comment by radare** [comment]
Done

**Comment by unixfreaxjp** [comment]
Thank you very much,
